services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3-3.14-bookworm
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    env_file: ["../.env"]
    networks:
      - otel-net
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: ["../.env"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - otel-net
  adot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ../otel-agent-config.yaml:/etc/otel-agent-config.yaml
      - /home/glen/.aws:/root/.aws:ro
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "4317:4317" # OTEL gRPC receiver
      - "4318:4318"
    networks:
      - otel-net
volumes:
  postgres_data:


networks:
  otel-net:
    external: true