name: tests
'on':
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: career_journal
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/career_journal
      OPENAI_API_KEY: test

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          
      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Initialize database
        run: |
          PGPASSWORD=postgres psql \
          -h localhost -U postgres -d career_journal \
          -f database_setup.sql

      - name: Run tests
        run: uv run pytest -v

  build-and-push-to-ecr:
    permissions:
      id-token: write
    runs-on: ubuntu-latest  
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::394151408055:role/GIthub-OIDC-Role
          aws-region: us-east-1

      - name: Login to Amazon ECR private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: l2c/journal-app
            IMAGE_TAG: latest
        run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG